name: Push

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build

  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: make test

  integration-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Integration tests
        run: make integration
