name: Test

on:
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make build

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unit tests
        run: make test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Integration tests
        run: make integration

  check-binary-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hash
        run: make hash

      - name: Commit Hash
        run: echo ${{ github.event.pull_request.head.sha }}
